"""Scientific figures and data products made from this run's resolved queries."""
from pathlib import Path
import json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from pxr import Usd
from .resolve import Resolver
def plots_and_products(root,out,records,targets):
    plt.rcParams.update({'font.family':'DejaVu Sans','axes.spines.top':False,'axes.spines.right':False,'axes.titleweight':'bold','axes.labelcolor':'#334b55','text.color':'#183641','figure.facecolor':'white','savefig.facecolor':'white','font.size':12})
    def save(fig,name):fig.savefig(out/name,dpi=170,bbox_inches='tight');plt.close(fig)
    n=records['tower-France_02-t0']['geometry'];fig,ax=plt.subplots(figsize=(9,6))
    for k,v in n.items():
        if '/Tower/' not in k:continue
        a=np.array(v);ax.scatter(a[::35,0]-648237.125,a[::35,1]-6862251.890,s=.4,c='#315661',alpha=.6)
    for label,xy in [('East control',(150,0)),('North control',(0,150)),('West control',(-150,0)),('South control',(0,-150))]:ax.scatter(*xy,s=35,c='#b55730');ax.annotate(label,xy,xytext=(6,6),textcoords='offset points',fontsize=10)
    ax.scatter(0,0,s=45,c='#132d38');ax.set(xlim=(-190,190),ylim=(-190,190),xlabel='Lambert-93 easting offset (m)',ylabel='Lambert-93 northing offset (m)',title='Eiffel footprint resolved in a named CRS');ax.set_aspect('equal');ax.grid(alpha=.16);fig.subplots_adjust(bottom=.24);fig.text(.13,.015,'Origin: E 648,237.125 m / N 6,862,251.890 m / IGN69 H 33.79 m.\nControl markers and flat ground are illustrative context, not surveyed site geometry.',fontsize=10);save(fig,'tower-plan.png')
    a=np.array(records['terrain-Colorado_03-t0']['geometry']['/Terrain/Breaklines']);s=Usd.Stage.Open(str(root/'scenes/terrain.usda'));counts=s.GetPrimAtPath('/Terrain/Breaklines').GetAttribute('curveVertexCounts').Get();starts=np.r_[0,np.cumsum(counts)];segments=[a[starts[i]:starts[i+1],:2]*1200/3937 for i in range(len(counts))];o=a[0,:2]*1200/3937
    fig,ax=plt.subplots(figsize=(10,6));lc=LineCollection([x-o for x in segments],linewidths=.55,cmap='terrain');lc.set_array(np.array([np.mean(a[starts[i]:starts[i+1],2])*1200/3937 for i in range(len(counts))]));ax.add_collection(lc);ax.autoscale();ax.set_aspect('equal');ax.set(xlabel='Calibrated site easting offset (m)',ylabel='Calibrated site northing offset (m)',title='Colorado: complete site calibration stays in WKT');fig.colorbar(lc,ax=ax,label='Site height (m, converted from US survey feet)');fig.subplots_adjust(bottom=.2);fig.text(.13,.015,'Original LandXML breaklines; N/E/H source order explicitly mapped to E/N/H. No invented TIN.',fontsize=10);save(fig,'colorado-terrain.png')
    a=np.array(records['railway-utm32-t0']['measurements']['/RailCoordinates.data:coordinates']);counts=np.load(root/'data/rail-topology.npz')['counts'];starts=np.r_[0,np.cumsum(counts)];o=a.mean(axis=0)
    fig,ax=plt.subplots(figsize=(10,6));ax.add_collection(LineCollection([a[starts[i]:starts[i+1],:2]-o[:2] for i in range(len(counts))],linewidths=.5,colors='#0c7f8c'));ax.autoscale();ax.set_aspect('equal');ax.set(xlabel='UTM 32 easting offset (m)',ylabel='UTM 32 northing offset (m)',title='Original railway: all coordinates resolved, source retained');ax.grid(alpha=.12);fig.text(.13,.01,'15,822 original vertices / 2,386 coordinate parts. Height interpretation is conditional.\nScientific query visualization; this figure is not a Hydra rendering claim.',fontsize=10);save(fig,'railway-query.png')
    s=Usd.Stage.Open(str(root/'scenes/city.usda'));p=s.GetPrimAtPath('/Image');values=np.array(p.GetAttribute('data:values').Get());a=np.array(records['city-utm31-t0']['measurements']['/Image.data:coordinates']);geo=np.array(records['city-geographic-t0']['measurements']['/Image.data:coordinates']);mask=values>.3
    fig,(ax,bx)=plt.subplots(1,2,figsize=(12,5));im=ax.imshow(values.reshape(64,64),origin='lower',cmap='YlGn',vmin=-.2,vmax=.7);ax.set(title='Analyze measurement values',xlabel='Image column',ylabel='Image row');fig.colorbar(im,ax=ax,label='Synthetic NDVI')
    bx.scatter(a[:,0],a[:,1],c=values,cmap='YlGn',s=7,vmin=-.2,vmax=.7);bx.scatter(a[mask,0],a[mask,1],s=1,c='#185d3a');bx.set_aspect('equal');bx.set(title='Return the selected locations',xlabel='UTM 31 easting (m)',ylabel='UTM 31 northing (m)');fig.suptitle('City imagery is data first; visualization is optional',fontweight='bold');fig.tight_layout();fig.text(.05,-.045,'Synthetic red/NIR image and 80 m ellipsoidal sample height; no real land-use inference. Scientific query visualization.',fontsize=10);save(fig,'city-analysis.png')
    features=[{'type':'Feature','geometry':{'type':'Point','coordinates':geo[i].tolist()},'properties':{'source_index':int(i),'ndvi':float(values[i]),'observation_time':0.,'origin':'synthetic demonstration'}} for i in np.where(mask)[0]]
    (out/'city-selected-features.geojson').write_text(json.dumps({'type':'FeatureCollection','features':features})+'\n')
    (out/'city-analysis-product.json').write_text(json.dumps({'output_crs_wkt':targets['utm31'],'source_indices':np.where(mask)[0].tolist(),'coordinates':a[mask].tolist(),'measurements':values[mask].tolist(),'observation_times':[0.]*int(mask.sum()),'origin':'Synthetic NDVI extraction; coordinates/values/times remain paired'})+'\n')
    s=Usd.Stage.Open(str(root/'scenes/climate.usda'));p=s.GetPrimAtPath('/Climate');v=np.array(p.GetAttribute('data:values').Get(0));v1=np.array(p.GetAttribute('data:values').Get(10));a=np.array(records['climate-ecef-t0']['measurements']['/Climate.data:coordinates']);g=np.array(records['climate-geographic-t0']['measurements']['/Climate.data:coordinates'])
    fig=plt.figure(figsize=(10,6));ax=fig.add_subplot(projection='3d');im=ax.scatter(a[:,0]/1e6,a[:,1]/1e6,a[:,2]/1e6,c=v,cmap='coolwarm',s=13,alpha=.92);ax.set_box_aspect((1,1,1));ax.set(xlabel='ECEF X (Mm)',ylabel='ECEF Y (Mm)',zlabel='ECEF Z (Mm)',title='Global coverage without one flattened tangent plane');ax.view_init(elev=18,azim=-32);fig.colorbar(im,ax=ax,shrink=.63,label='Original scalar values (unit not authored in source file)');fig.text(.12,.02,'2,664 original samples; assumed zero ellipsoidal height. Matplotlib query visualization, not Hydra.',fontsize=10);save(fig,'global-ecef.png')
    # Arrange only the plotting copy by the resolved longitude/latitude; source indices stay intact.
    lons=np.unique(g[:,0]);lats=np.unique(g[:,1]);grid=np.full((len(lats),len(lons)),np.nan);delta=grid.copy()
    xi=np.searchsorted(lons,g[:,0]);yi=np.searchsorted(lats,g[:,1]);grid[yi,xi]=v;delta[yi,xi]=v1-v
    assert np.isfinite(grid).all()
    fig,(ax,bx)=plt.subplots(2,1,figsize=(11,6.5));im=ax.pcolormesh(lons,lats,grid,cmap='coolwarm',shading='nearest');ax.set(title='Original scalar field',ylabel='Latitude');fig.colorbar(im,ax=ax,label='Source value');im=bx.pcolormesh(lons,lats,delta,cmap='RdBu_r',shading='nearest',vmin=-1,vmax=1);bx.set(title='Explicitly synthetic second-time change',xlabel='Longitude',ylabel='Latitude');fig.colorbar(im,ax=bx,label='Synthetic value change');fig.tight_layout();fig.text(.12,-.015,'Recorded values and coordinate indices remain paired. This generated time does not establish a climate trend.',fontsize=10);save(fig,'climate-analysis.png')
    (out/'climate-analysis-product.json').write_text(json.dumps({'output_crs_wkt':targets['ecef'],'coordinates':a.tolist(),'values_time_0':v.tolist(),'values_time_10':v1.tolist(),'observation_times':[0.,10.],'second_time_origin':'synthetic perturbation of original field'})+'\n')
    return {'city':{'samples':len(values),'selected_features':int(mask.sum()),'source_values_preserved':True,'synthetic':True},'climate':{'samples':len(v),'coordinate_extent':'global ECEF','positions_fixed_between_times':True,'second_time_synthetic':True,'source_values_preserved':True},'railway':{'original_vertices':len(counts) and int(counts.sum()),'coordinate_parts':len(counts),'all_source_coordinates_preserved':True,'height_reference_conditional':True}}
